# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_operations.ipynb.

# %% auto 0
__all__ = ['clean_code', 'big_o', 'runtime', 'bugs']

# %% ../nbs/01_operations.ipynb 4
from .openai_api import *
import openai

# %% ../nbs/01_operations.ipynb 11
# Readability & maintainability
def clean_code(python_file:str) -> str:
    return clean_code

# %% ../nbs/01_operations.ipynb 12
def big_o():
    pass

# %% ../nbs/01_operations.ipynb 13
def runtime():
    pass

# %% ../nbs/01_operations.ipynb 14
def bugs():
    pass 
