# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_operations.ipynb.

# %% auto 0
__all__ = ['clean_code', 'big_o', 'runtime', 'bugs']

# %% ../nbs/01_operations.ipynb 4
from .openai_api import *
import openai

# %% ../nbs/01_operations.ipynb 7
# Readability & maintainability
def clean_code(python_file:str) -> str:
    return optimization(python_file, metric='clean code')

# %% ../nbs/01_operations.ipynb 9
def big_o(python_file:str):
    return optimization(python_file, metric='big O space and time complexity')

# %% ../nbs/01_operations.ipynb 10
def runtime(python_file:str):
    return optimization(python_file, metric='runtime')

# %% ../nbs/01_operations.ipynb 11
def bugs(python_file:str):
    return optimization(python_file, metric='bugs') 
