# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/gpt-api',
                'doc_host': 'https://Dalton.github.io',
                'git_url': 'https://github.com/Dalton/gpt-api',
                'lib_path': 'gpt_api'},
  'syms': {'gpt_api.core': {'gpt_api.core.foo': ('core.html#foo', 'gpt_api/core.py')}}}
