# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/gpt-api',
                'doc_host': 'https://Dalton.github.io',
                'git_url': 'https://github.com/Dalton/gpt-api',
                'lib_path': 'gpt_api'},
  'syms': { 'gpt_api.cli': {'gpt_api.cli.foo': ('cli.html#foo', 'gpt_api/cli.py')},
            'gpt_api.core': {'gpt_api.core.foo': ('cli.html#foo', 'gpt_api/core.py')},
            'gpt_api.openai_api': { 'gpt_api.openai_api.foo': ('openai_api.html#foo', 'gpt_api/openai_api.py'),
                                    'gpt_api.openai_api.load_api_key': ('openai_api.html#load_api_key', 'gpt_api/openai_api.py')},
            'gpt_api.parser': {'gpt_api.parser.foo': ('parser.html#foo', 'gpt_api/parser.py')},
            'gpt_api.tests': {'gpt_api.tests.foo': ('tests.html#foo', 'gpt_api/tests.py')}}}
