# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_cli.ipynb.

# %% auto 0
__all__ = ['dotenv_path', 'API_KEY', 'foo']

# %% ../nbs/01_cli.ipynb 3
def foo(): pass

# %% ../nbs/01_cli.ipynb 6
dotenv_path = Path('../../.env')
load_dotenv(dotenv_path)
API_KEY = os.getenv('API_KEY')
openai.api_key = API_KEY
